services:
  db:
    image: mysql:8.3.0
    container_name: mysql_db
    command: mysqld --default_authentication_plugin=mysql_native_password

    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: studyManagement
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: ${DB_PORT}

    ports:
      - ${DB_PORT}

    expose:
      - ${DB_PORT}

    networks:
      - study_management_network

  study_management:

    image: guilhermebauer/study_management:latest
    container_name: study_management
#    build: .
#
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${DB_NAME}?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${EXPOSE_PORT}:${CONTAINER_PORT}"


    depends_on:
      - db

    networks:
      - study_management_network

networks:
  study_management_network:
    driver: bridge